# Generated by Django 6.0.6 on 2026-06-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_imageannonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='image',
            field=models.ImageField(upload_to='annonces/covers/'),
        ),
        migrations.AlterField(
            model_name='imageannonce',
            name='image',
            field=models.ImageField(upload_to='annonces/gallery/'),
        ),
    ]
