# Generated by Django 6.0.6 on 2026-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_annonce_image_alter_imageannonce_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-premium', '-cree_le']},
        ),
        migrations.AddField(
            model_name='annonce',
            name='boost_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
